### ISSUE TITLE
Connection refused to qbittorrent client

### ISSUE THREAD

**Issue by yur1xpp** [Schaka/rarrnomore#3]
I have issue connecting to the download client (qbittorrent), my system is headless ubuntu.

Others connected with no issue to the client address (http://localhost:8088/), including the *arr itself, so did the [qbt-cli tool ](https://github.com/fedarovich/qbittorrent-cli/). Deployed using this command:
```
sudo docker run -d --name='rarrnomore' -e HOST_CONTAINERNAME="rarrnomore" -p 8978:8978 -v '/home/myusername/docker/rarrnomore/config':'/config':'rw' 'schaka/rarrnomore'
```

I'm not sure if this has anything to do with the `application.yml`, because I used special characters for the password, but they are wrapped in single quote. I even changed the WEBUI password to non-special characters only, the same issue persists. My configs: (the name `qbittorrent` is correct)

```
server:
  port: 8978

clients:
  sonarr:
    url: "http://localhost:8989"
    api-key: "REDACTED"
  radarr:
    url: "http://localhost:7878"
    api-key: "REDACTED"
  torrent:
    type: QBITTORRENT
    name: qbittorrent
    url: "http://localhost:8088"
    username: REDACTED
    password: 'REDACTED'
logging:
  level:
    com.github.schaka: TRACE
```
And the logs:
```
2023-06-01T14:19:28.976Z TRACE 1 --- [   scheduling-1] c.g.s.rarrnomore.torrent.TorrentManager  : Attempting to reject or resume torrent ([REDACTED]) ([REDACTED])
2023-06-01T14:19:29.003Z ERROR 1 --- [   scheduling-1] c.g.s.r.t.qbit.QbitAuthInterceptor       : Error connecting to torrent client

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8088/api/v2/auth/login": Connection refused
        at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:512) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.attemptAuthentication(QbitAuthInterceptor.kt:48) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.intercept(QbitAuthInterceptor.kt:31) ~[classes/:na]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:87) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:71) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QBittorrentService.enrichTorrentInfo(QBittorrentService.kt:26) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.rejectOrResumeTorrent(TorrentManager.kt:96) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.tryToProcess(TorrentManager.kt:74) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:51) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na]
        at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
        at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:na]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        ... 25 common frames omitted
```

**Comment by Schaka** [comment]
The password shouldn't be an issue, although I recommend double quotes.
I'm not sure how your containers are set up. Localhost pertains to the docker container itself - only rarrnomore will be running here. If you want to run all your containers on the host (i.e. your Linux machine) you need to pass network type host to the container as you start like, like so:

`sudo docker run -d --name='rarrnomore' --net=host -e HOST_CONTAINERNAME="rarrnomore" -p 8978:8978 -v '/home/myusername/docker/rarrnomore/config':'/config':'rw' 'schaka/rarrnomore'`

**Comment by yur1xpp** [comment]
I didn't know that, specifying  `--net=host` seems to solve the issue. Thanks for the tip. 

I have developed a webhook+bash script to replicate your idea in the meantime, seems to works pretty well. Thanks for the inspiration haha.
