### ISSUE TITLE
application.yml not being found

### ISSUE THREAD

**Issue by Lucifer1903** [Schaka/rarrnomore#4]
Rarrnomore isn't working I believe this is the issue:
`[main] c.g.s.r.RarrnomoreApplicationKt          : No active profile set, falling back to 1 default profile: "default"
I think this means that it can't find application.yml`

these are the settings I'm running Rarrnomore with:
`docker run -d --restart unless-stopped --name='rarrnomore_private' -e HOST_CONTAINERNAME="rarrnomore_private" -p 8979:8978 -v '/home/user/docker/rarrnomore_private/config':'/config':'rw' 'schaka/rarrnomore'`

application.yml is here `/home/user/docker/rarrnomore_private/config/application.yml`
I've even set all the permissions to 777 in case that was the issue.

Here is a snippet of the log file, I think it can't connect to qbittorent because it can't read application.yml
 

`2023-06-03T16:01:54.648Z ERROR 1 --- [   scheduling-1] c.g.s.rarrnomore.torrent.TorrentManager  : Processing torrent Valeria S03 MULTI 1080p WEB.x264 failed`

`java.lang.IllegalStateException: Can't connect to QBittorrent
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.attemptAuthentication(QbitAuthInterceptor.kt:57) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.intercept(QbitAuthInterceptor.kt:31) ~[classes/:na]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:87) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:71) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QBittorrentService.enrichTorrentInfo(QBittorrentService.kt:26) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.rejectOrResumeTorrent(TorrentManager.kt:96) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.tryToProcess(TorrentManager.kt:74) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:51) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]`

`2023-06-03T16:01:54.648Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task`

`java.lang.UnsupportedOperationException: null
        at java.base/java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source) ~[na:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:43) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]`

Any idea on what I'm doing wrong?

**Comment by Lucifer1903** [comment]
so I was trying to run 2 instances of rarrnomore, one for public torrents and one for private. 
I decided to start over from scratch and just get one working first.

I've tried running rarrnomore with  `--net=host` as seen below

`docker run -d --restart unless-stopped --net=host --name='rarrnomore' -e HOST_CONTAINERNAME="rarrnomore" -p 8978:8978 -v '/home/jelly/docker/rarrnomore/config':'/config':'rw' 'schaka/rarrnomore'`

but it's still not working.

`2023-06-03T16:54:57.026Z ERROR 1 --- [   scheduling-1] c.g.s.rarrnomore.torrent.TorrentManager  : Processing torrent Valeria S03 MULTI 1080p WEB.x264 failed`

`org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "Not Found"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:112) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QBittorrentService.enrichTorrentInfo(QBittorrentService.kt:26) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.rejectOrResumeTorrent(TorrentManager.kt:96) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.tryToProcess(TorrentManager.kt:74) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:51) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]`

`2023-06-03T16:54:57.026Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task`

`java.lang.UnsupportedOperationException: null
        at java.base/java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source) ~[na:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:43) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]`

**Comment by Schaka** [comment]
I can't say what might be wrong about your network setup. Everything looks correct to me, but it seems like the important info like host names was removed from the logs.

The last exception is because you're not on the latest version of the container, so make sure you pull :latest again.

**Comment by Lucifer1903** [comment]
Thanks, I'll try to Pull :latest and see if that helps. 

Is it normal to the this in the logs at startup? 
`[main] c.g.s.r.RarrnomoreApplicationKt          : No active profile set, falling back to 1 default profile: "default"`

**Comment by Lucifer1903** [comment]
@Schaka it's working now. Thanks!

**Comment by Schaka** [comment]
For documentation purposes, the profile logging is correct. Profiles are part of spring-boot, which I'm using here.
However, no profiles are in use because they're simply not needed.

**Comment by helenclarko** [comment]
I'm also getting this issue, but I've noticed it's trying to access localhost:8080/api/v2/auth, which makes me think it's using a defult config and not the one I've set.

```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8080/api/v2/auth/login": Connection refused
        at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:512) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.attemptAuthentication(QbitAuthInterceptor.kt:48) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.intercept(QbitAuthInterceptor.kt:31) ~[classes/:na]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:87) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:71) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QBittorrentService.enrichTorrentInfo(QBittorrentService.kt:26) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.rejectOrResumeTorrent(TorrentManager.kt:98) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.tryToProcess(TorrentManager.kt:76) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:52) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na]
        at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
        at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:na]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        ... 25 common frames omitted

2024-01-27T19:25:12.851Z ERROR 1 --- [   scheduling-1] c.g.s.rarrnomore.torrent.TorrentManager  : Unexpected exception occurred, do not retry

java.lang.IllegalStateException: Can't connect to QBittorrent
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.attemptAuthentication(QbitAuthInterceptor.kt:57) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.intercept(QbitAuthInterceptor.kt:31) ~[classes/:na]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:87) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:71) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QBittorrentService.enrichTorrentInfo(QBittorrentService.kt:26) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.rejectOrResumeTorrent(TorrentManager.kt:98) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.tryToProcess(TorrentManager.kt:76) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:52) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-01-27T19:25:17.852Z ERROR 1 --- [   scheduling-1] c.g.s.rarrnomore.torrent.TorrentManager  : Processing torrent The Walking Dead (2010) S08 (1080p AMZN WEB-DL H265 SDR DDP 5 1 English - DarQ) failed

java.lang.IllegalStateException: Can't connect to QBittorrent
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.attemptAuthentication(QbitAuthInterceptor.kt:57) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.qbit.QbitAuthInterceptor.intercept(QbitAuthInterceptor.kt:31) ~[classes/:na]
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:87) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:71) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.8.jar:6.0.8]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.8.jar:6.0.8]
        at com.github.schaka.rarrnomore.torrent.qbit.QBittorrentService.enrichTorrentInfo(QBittorrentService.kt:26) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.rejectOrResumeTorrent(TorrentManager.kt:98) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.tryToProcess(TorrentManager.kt:76) ~[classes/:na]
        at com.github.schaka.rarrnomore.torrent.TorrentManager.processServarrQueue(TorrentManager.kt:52) ~[classes/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-6.0.8.jar:6.0.8]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.8.jar:6.0.8]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
 ```
 
 @Schaka Should I post this here?

**Comment by helenclarko** [comment]
Nevermind, I'm an idiot and had the docker run command around the wrong way.
I had it using the config from the wrong directory entirely.
